### ISSUE TITLE
what is the 'train_features.pickle'

### ISSUE THREAD

**Issue by doorteeth** [tayfunates/personreid-rn#1]
https://github.com/tayfunates/personreid-rn/blob/57e3cc403ec844d73b8badc60ab4f72961d8dd11/src/data/market1501.py#L32

hi,tay. I meet a question reading your code. What is the 'train_features.pickle', and how did it appear?
Can you tell me?Thank you very much.

**Comment by tayfunates** [comment]
Hi, It is a pickle file for pretrained features of train set to speed up. I will not able to update the feature files to github.

**Comment by doorteeth** [comment]
ok, thank you very much.
